name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-agplv3:
    uses: ./.github/workflows/test.yml

  test-with-extra:
    uses: ./.github/workflows/test.yml
    with:
      with_extra: "1"

  test-cloud:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      with_extra: "1"
      keila_cloud: "1"

  build:
    name: Build and push Docker image
    if: github.ref == 'refs/heads/main'
    needs:
      - test-agplv3
      - test-with-extra
      - test-cloud
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_PAT }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./ops/Dockerfile
          build-args: |
            WITH_EXTRA=1
            KEILA_CLOUD=1
            "KEILA_CLOUD_LICENSE=${{ secrets.KEILA_CLOUD_LICENSE }}"
          tags: |
            ghcr.io/pentacent/keila:cloud-latest
            ghcr.io/pentacent/keila:cloud-sha-${{ github.sha }}
          labels: |
            service=keila
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
